version: "3"
services:
  userdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
  pm_user_management:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - userdb